import React from "react";
export const users = [
  {
    id: "T0001",
    name: "Tony Reichert",
    position: "經理",
    company: "中華聯合商務",
    department: "IT部",
    status: "在職",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/1.png",
    email: "tony.reichert@example.com",
  },
  {
    id: "T0002",
    name: "Zoey Lang",
    position: "經理",
    company: "中華聯合商務",
    department: "IT部",
    status: "在職",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/1.png",
    email: "zoey.lang@example.com",
  },
  {
    id: "T0003",
    name: "Jane Fisher",
    position: "經理",
    company: "中華聯合商務",
    department: "IT部",
    status: "在職",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/2.png",
    email: "jane.fisher@example.com",
  },
  {
    id: "T0004",
    name: "William Howard",
    position: "經理",
    company: "中華聯合商務",
    department: "IT部",
    status: "在職",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/2.png",
    email: "william.howard@example.com",
  },
  {
    id: "T0005",
    name: "Mia Robinson",
    position: "經理",
    company: "中華聯合商務",
    department: "IT部",
    status: "在職",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/12.png",
    email: "mia.robinson@example.com",
  },
  {
    id: "T0006",
    name: "Mssia Robinson",
    position: "經理",
    company: "中華聯合商務",
    department: "IT部",
    status: "在職",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/12.png",
    email: "mia.robinson@example.com",
  },
  {
    id: "T0007",
    name: "ssMia Robinson",
    position: "經理",
    company: "中華聯合商務",
    department: "IT部",
    status: "在職",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/12.png",
    email: "mia.robinson@example.com",
  },
 
];
